apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7nng
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-7nng@sha256:135752771157f26e2e188bdd82d35d387ed0fbbd2a5aeae92450623f8717d721
        name: my-nodejs
        resources: {}
status: {}
